[project]
name = "weather-prediction1"
version = "0.1.0"
description = "WeatherAI powered by CrewAI, Open-Meteo, and Groq"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai==1.15.22",
    "python-dotenv==1.2.3",
    "requests==2.34.2",
    "streamlit==1.64.0",
    "litellm==1.102.0",
]

[project.scripts]
weather-prediction1 = "weather_prediction1:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
